{ pkgs, ... }:
{
  home.packages = with pkgs; [
    _3proxy
    acquire
    ad-miner
    adenum
    aesfix
    aeskeyfind
    aespipe
    afflib
    aflplusplus
    aiodnsbrute
    aircrack-ng
    airgeddon
    amass
    amoco
    androguard
    apachetomcatscanner
    apkid
    apkleaks
    apktool
    ares-rs
    argus
    arjun
    arp-scan
    arping
    arpoison
    asn
    asnmap
    assetfinder
    atftp
    autopsy
    bamf
    batctl
    bettercap
    bind
    binwalk
    bkcrack
    bloodhound
    bloodhound-py
    bmaptool
    brakeman
    bruteforce-luks
    brutespray
    bsdiff
    bulk_extractor
    bully
    burpsuite
    bvi
    bytecode-viewer
    cadaver
    cantoolz
    capstone
    cargo-ndk
    certgraph
    certipy
    certsync
    cewl
    cfr
    chainsaw
    chaos
    checkpwn
    chipsec
    chisel
    chntpw
    clairvoyance
    clamav
    cloudlist
    cmospwd
    cntlm
    coercer
    commix
    corkscrew
    cowpatty
    crackle
    (pkgs.crackql.overrideAttrs (old: {
      postInstall =
        (old.postInstall or "")
        + "\n        mv $out/lib/python3.13/site-packages/version.py $out/lib/python3.13/site-packages/crackql_version.py";
    }))
    creds
    crlfuzz
    crowbar
    crunch
    cryptsetup
    ctypes_sh
    cutter
    dalfox
    darkstat
    dc3dd
    dcfldd
    ddosify
    ddrescue
    detect-secrets
    dex2jar
    dirb
    dirstalk
    dislocker
    dive
    dmg2img
    dnschef
    dnsenum
    dnsmasq
    dnsrecon
    dnstracer
    dnstwist
    dnsx
    nomore403
    doona
    dorkscout
    dump1090-fa
    edb
    elfkickers
    elfutils
    enum4linux
    enum4linux-ng
    eresi
    etherape
    ettercap
    evil-winrm
    evillimiter
    exabgp
    exiftool
    exploitdb
    ext4magic
    extundelete
    fatcat
    fcrackzip
    feroxbuster
    ffuf
    fierce
    file
    firefox_decrypt
    firewalk
    flare-floss
    flasm
    foremost
    fping
    freeipmi
    freeradius
    freerdp
    frida-tools
    fscan
    fwbuilder
    gau
    gdb
    gdbgui
    geoip
    ghauri
    ghdorker
    ghidra
    ghost
    girsh
    git-hound
    gitleaks
    gnutls
    go-cve-search
    gobuster
    gomapenum
    gospider
    gowitness
    graphinder
    graphqlmap
    graphw00f
    gsocket
    hackrf
    hakrawler
    hash-identifier
    hash_extender
    hashcat
    hashcat-utils
    hashdeep
    hashpump
    hashrat
    hcxdumptool
    hcxtools
    hexbinhex
    holehe
    honggfuzz
    hostapd-mana
    hping
    hstsparser
    httping
    httprobe
    httptunnel
    httpx
    i2pd
    iaito
    ike-scan
    interactsh
    iodine
    ipmitool
    iputils
    jadx
    jaeles
    jnetmap
    john
    johnny
    joomscan
    jsbeautifier
    jwt-hack
    kalibrate-rtl
    katana
    kerbrute
    kismet
    kiterunner
    knockpy
    ldapdomaindump
    ldeep
    libargon2
    libbde
    libewf
    libgcrypt
    libosmocore
    libpst
    lief
    ligolo-ng
    linux-exploit-suggester
    lldb
    loadlibrary
    ltrace
    mac-robber
    macchanger
    mailsend
    maltego
    mapcidr
    masscan
    mdk4
    medusa
    metabigor
    metasploit
    mfcuk
    mfoc
    miredo
    mitmproxy
    mitmproxy2swagger
    mongoaudit
    monsoon
    ms-sys
    mtr
    mubeng
    multimon-ng
    naabu
    nasm
    netdiscover
    netexec
    netmask
    netsniff-ng
    nfdump
    ngrep
    ngrok
    nikto
    nmap
    nosqli
    ntfs3g
    ntlmrecon
    nuclei
    obfs4
    octosuite
    oletools
    onesixtyone
    osquery
    osslsigncode
    ostinato
    p0f
    packer
    parsero
    payloadsallthethings
    pcapfix
    pdf-parser
    pdfcrack
    pe-bear
    pev
    photon
    phrasendrescher
    pixd
    pixiewps
    plecost
    pmacct
    pngcheck
    powersploit
    procdump
    procyon
    prowler
    proxify
    proxmark3
    proxychains-ng
    psudohash
    pwnat
    pwncat
    pwntools
    python313Packages.arsenic
    python313Packages.certipy-ad
    python313Packages.distorm3
    python313Packages.dnspython
    python313Packages.frida-python
    python313Packages.impacket
    python313Packages.ldapdomaindump
    python313Packages.minidump
    python313Packages.minikerberos
    python313Packages.myjwt
    python313Packages.netmap
    python313Packages.pcodedmp
    python313Packages.pwntools
    python313Packages.pyaxmlparser
    python313Packages.pyjsparser
    python313Packages.pypykatz
    python313Packages.ropper
    python313Packages.scapy
    python313Packages.shodan
    python313Packages.spyse-python
    python313Packages.sshtunnel
    python313Packages.thefuzz
    python313Packages.torpy
    python313Packages.vt-py
    python313Packages.websockify
    python313Packages.yara-python
    quark-engine
    radamsa
    radare2
    rarcrack
    rathole
    reaverwps-t6x
    recoverjpeg
    redsocks
    regripper
    responder
    rinetd
    rita
    rizin
    rizinPlugins.rz-ghidra
    rr
    ruler
    rustcat
    rustscan
    safecopy
    saleae-logic-2
    samplicator
    scalpel
    seclists
    sha1collisiondetection
    shellnoob
    sherlock
    siege
    sleuthkit
    slowhttptest
    slowlorust
    smbmap
    sn0int
    snallygaster
    sniffglue
    snmpcheck
    snort
    snow
    snscrape
    snyk
    soapui
    socat
    social-engineer-toolkit
    socialscan
    spiped
    sqlmap
    ssdeep
    ssh-mitm
    sshuttle
    ssldump
    sslh
    sslscan
    sslsplit
    stacs
    strace
    stunnel
    subfinder
    subjs
    suricata
    swaks
    sysdig
    tcpdump
    tcpflow
    tcpreplay
    tcptraceroute
    tell-me-your-secrets
    testdisk
    testssl
    tfsec
    thc-hydra
    thc-ipv6
    theharvester
    tinc
    tinyproxy
    tor
    torsocks
    tracee
    traceroute
    trivy
    truecrack
    trufflehog
    tshark
    udis86
    udp2raw
    udpreplay
    udptunnel
    uncover
    upx
    usbrip
    valgrind
    veracrypt
    volatility3
    vt-cli
    wafw00f
    wapiti
    wavemon
    wcc
    webanalyze
    websploit
    wfuzz
    whatweb
    whispers
    wifite2
    termshark
    wireshark-cli

    wpscan
    wstunnel
    wuzz
    wxhexeditor
    xortool
    yara
    yersinia
    zap
    zdns
    zgrab2
    zmap
    zssh
    zulu
    zzuf
  ];
}
